
/**
Constructor
Do not call Function in Constructor.
*/
class naverProject000()
{
	super();

	//TODO:edit here

}
extends AView;


function naverProject000*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function naverProject000*onInitDone()
{
	super.onInitDone();
	this.tabview.addTab('탭1','','tab1');

	//TODO:edit here

};

function naverProject000*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

function naverProject000*onATabView1Swipe(comp, info, e)
{

	//TODO:edit here

};
