
/**
Constructor
Do not call Function in Constructor.
*/
class NaverCopy()
{
	super();

	//TODO:edit here

}
extends AView;


function NaverCopy*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function NaverCopy*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function NaverCopy*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
