
/**
Constructor
Do not call Function in Constructor.
*/
class PlusOne()
{
	super();

	//TODO:edit here

}
extends AView;


function PlusOne*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function PlusOne*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function PlusOne*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
