
/**
Constructor
Do not call Function in Constructor.
*/
class Shopping()
{
	super();

	//TODO:edit here

}
extends AView;


function Shopping*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function Shopping*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function Shopping*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

