
/**
Constructor
Do not call Function in Constructor.
*/
class TestView2()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
