
/**
Constructor
Do not call Function in Constructor.
*/
class TestView3()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
