
/**
Constructor
Do not call Function in Constructor.
*/
class TestView5()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView5*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView5*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView5*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
