
/**
Constructor
Do not call Function in Constructor.
*/
class TestView9()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView9*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView9*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView9*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
