
/**
Constructor
Do not call Function in Constructor.
*/
class TestView4()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView4*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView4*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView4*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
