
/**
Constructor
Do not call Function in Constructor.
*/
class TestView7()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView7*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView7*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView7*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
