
/**
Constructor
Do not call Function in Constructor.
*/
class TestView5Copy()
{
	super();

	//TODO:edit here

}
extends AView;


function TestView5Copy*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TestView5Copy*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TestView5Copy*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
